version: "3.7"

services:
  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_DB: "django_project"
      POSTGRES_USER: "django_project"
      POSTGRES_PASSWORD: "django_project"
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/

volumes:
  postgres_data: